name: mbc_common
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  dio_http_formatter: ^3.3.0
  go_router: 14.3.0
  flutter_secure_storage: ^9.2.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  multiple_result: ^5.1.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  retrofit_generator: '>=8.1.2'
  json_serializable: '^6.8.0'
  freezed: ^2.5.7
  riverpod_generator: ^2.4.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - lang/en.json
    - lang/fr.json

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 700
    - family: BreeSerif
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

